services:
  api:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes: 
      - ./app:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  postgres:
    image: postgres:14.15-alpine3.21
    env_file:
      - .env
    ports:
      - "5432:5432"