# Generated by Django 5.2.4 on 2025-07-28 13:06

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_emprestimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='devolvido_em',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='emprestado_em',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='vencimento_em',
            field=models.DateField(default=datetime.date(2025, 8, 4)),
        ),
    ]
