# Generated by Django 5.2.4 on 2025-07-29 17:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_emprestimo_devolvido_em_emprestimo_emprestado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to='core.livro'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='vencimento_em',
            field=models.DateField(default=datetime.date(2025, 8, 5)),
        ),
    ]
